### ISSUE TITLE
BlazorML5/wwwroot folder missing

### ISSUE THREAD

**Issue by GeorgeS2019** [sps014/BlazorML5#12]
[wwwroot](https://github.com/sps014/BlazorML5/tree/net5/BlazorML5/wwwroot)

**Comment by GeorgeS2019** [comment]
Need to reverse some of the merge

https://github.com/sps014/BlazorML5/pull/9

**Comment by sps014** [comment]
This is by design and we no longer need a wwwroot folder all code is written with [BlazorBindGen wrappers](https://github.com/sps014/BlazorML5/blob/master/BlazorML5/).
