### ISSUE TITLE
Offline model and training in device

### ISSUE THREAD

**Issue by Esther2013** [sps014/BlazorML5#8]
Hi @sps014 

I'm curious in if it's possible to add offline model and training capability in BlazorML5 by utiliizing the power of [TensorFlow .NET](https://github.com/SciSharp/TensorFlow.NET)?

**Comment by sps014** [comment]
1.  Models are already cached , they are loaded once . You can also load custom downloaded models.
You can read more [here.](https://github.com/ml5js/ml5-library/issues/478)

2. Tensorflow.Net is a different story, in Blazor Wasm Tensorflow.JS is a better a option, i am not sure if Tensorflow.Net is supported on Blazor and TF.Net  adds extra overhead of python runtime.  
 Once Blazor enhances `IJSUnmarshalledRuntime` we can  provide TFJS binding for C# , current `IJSUnmarshalledRuntime` is much more limiting in terms of capabilities (shared Memory).
